baseURL = 'https://fsm-foundry.github.io/docs/'
title = 'FSM Foundry Docs'
theme = 'hugo-book'

disablePathToLower = true
enableGitInfo = true

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
  [markup.highlight]
    style = 'base16-snazzy'

[params]
  BookTheme = 'light'
  BookSection = 'docs'
  BookSearch = true
  BookToC = true
  BookRepo = 'https://github.com/fsm-foundry/docs'
  BookPortableLinks = false
  BookServiceWorker = false
  BookComments = false
